title: The Reduction
email: jblonchek@gmail.com
title: The Reduction
description: simple takes on complex things
baseurl: /
url: http://www.thereduction.github.io
permalink: pretty

twitter_username: jblonchek

# Build settings
highlighter: rouge
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

  